AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: WhatsApp Webhook (API Gateway HTTP API + Lambda)

Globals:
  Function:
    Runtime: python3.12
    Timeout: 10
    MemorySize: 256
    Tracing: Active
    Architectures: [ x86_64 ]
    Environment:
      Variables:
        VERIFY_TOKEN: dev-bot-verify-token
        APP_SECRET:  dev-bot-meta-api-key
        PHONE_ID: dev-bot-phone-number-id
        USER_TOKEN: dev-bot-system-user-token

Resources:
  WebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./whatsapp-bot
      Handler: post_data.post_handler
      Role: arn:aws:iam::430118830579:role/bot-execution-role

  VerifyBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./whatsapp-bot
      Handler: app.get_handler
      Role: arn:aws:iam::430118830579:role/bot-execution-role