openapi: "3.0.1"
info:
  title: "divya-sutra-api-dev"
  description: "Dev API fort Divya Sutra"
  version: "2025-12-17T08:47:08Z"
servers:
- url: "https://8hurg54gn8.execute-api.ap-south-1.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: "dev"
paths:
  /api/v1/divyasutra/store/cart/{cartId}:
    get:
      parameters:
      - name: "cartId"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
  /api/v1/divyasutra/store/user:
    get:
      parameters:
      - name: "phone"
        in: "query"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
    post:
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
  /api/v1/divyasutra/store/cart:
    post:
      parameters:
      - name: "userId"
        in: "query"
        schema:
          type: "string"
      - name: "source"
        in: "query"
        schema:
          type: "string"
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
  /api/v1/divyasutra/bot:
    get:
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
    post:
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
  /api/v1/divyasutra/store/product:
    get:
      parameters:
      - name: "category"
        in: "query"
        schema:
          type: "string"
      - name: "limit"
        in: "query"
        schema:
          type: "string"
      - name: "page"
        in: "query"
        schema:
          type: "string"
      - name: "search"
        in: "query"
        schema:
          type: "string"
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
    post:
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
  /api/v1/divyasutra/store/cart/{cartId}/{userId}:
    get:
      parameters:
      - name: "userId"
        in: "path"
        required: true
        schema:
          type: "string"
      - name: "cartId"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
  /api/v1/divyasutra/store/user/{userId}:
    get:
      parameters:
      - name: "userId"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
    patch:
      parameters:
      - name: "userId"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
  /api/v1/divyasutra/store/cart/{cartId}/items:
    post:
      parameters:
      - name: "cartId"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
  /api/v1/divyasutra/store/order:
    get:
      parameters:
      - name: "userId"
        in: "query"
        schema:
          type: "string"
      - name: "phoneNumber"
        in: "query"
        schema:
          type: "string"
      - name: "status"
        in: "query"
        schema:
          type: "string"
      - name: "limit"
        in: "query"
        schema:
          type: "string"
      - name: "page"
        in: "query"
        schema:
          type: "string"
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
    post:
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
  /api/v1/divyasutra/store/product/{id}:
    get:
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
    put:
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
  /api/v1/divyasutra/store/cart/coupon:
    post:
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
  /api/v1/divyasutra/store/cart/{cartId}/items/{itemId}/{userId}:
    put:
      parameters:
      - name: "itemId"
        in: "path"
        required: true
        schema:
          type: "string"
      - name: "userId"
        in: "path"
        required: true
        schema:
          type: "string"
      - name: "cartId"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
    delete:
      parameters:
      - name: "itemId"
        in: "path"
        required: true
        schema:
          type: "string"
      - name: "userId"
        in: "path"
        required: true
        schema:
          type: "string"
      - name: "cartId"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
  /api/v1/divyasutra/store/order/{orderId}:
    get:
      parameters:
      - name: "orderId"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
  /api/v1/divyasutra/store/order/{orderId}/status:
    put:
      parameters:
      - name: "orderId"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
components:
  schemas:
    Empty:
      title: "Empty Schema"
      type: "object"
x-amazon-apigateway-security-policy: "SecurityPolicy_TLS13_1_3_2025_09"
x-amazon-apigateway-endpoint-access-mode: "BASIC"
